In [ ]:
import numpy as np

A = np.array([[-2,-3,2,3],
              [-4,-6,6,6],
              [-2,0,4,6],
              [4,3,-8,-6]])

b = np.array([[10],
              [20],
              [10],
              [-17]])


print(A)
print(b)

[[-2 -3  2  3]
 [-4 -6  6  6]
 [-2  0  4  6]
 [ 4  3 -8 -6]]
[[ 10]
 [ 20]
 [ 10]
 [-17]]


In [ ]:
b1 = b.astype(float)
print(b1)

[[ 10.]
 [ 20.]
 [ 10.]
 [-17.]]


In [ ]:
MA = np.concatenate((A,b),axis=1)
print(MA)

[[ -2  -3   2   3  10]
 [ -4  -6   6   6  20]
 [ -2   0   4   6  10]
 [  4   3  -8  -6 -17]]


In [ ]:
print(A[1,2])

6


In [ ]:
U = MA[:,0:-1]
print(U)

[[-2 -3  2  3]
 [-4 -6  6  6]
 [-2  0  4  6]
 [ 4  3 -8 -6]]


In [ ]:
d = MA[:,-1]
print(d)

[ 10  20  10 -17]


In [ ]:
import numpy as np

def pos_def(A):
  return np.all(np.linalg.eigvals(A) > 0)


A = np.array([[2,0,0],
              [1,1,2],
              [1,-1,4]])

print(pos_def(A))

True


In [ ]:
import numpy as np

def diag_dominante(X):
  D = np.diag(np.abs(X))
  S = np.sum(np.abs(X), axis = 1) - D
  if np.all(D > S):
    print('Es una matriz diagonal dominante')
  else:
    print('No es diagonal domminante')

A = np.array([[12,-3,2,3],
              [-1,-16,6,6],
              [-2,0,14,6],
              [4,3,-1,-16]])

print('Diagonal de la matrix A', np.diag(A))
diag_dominante(A)

Diagonal de la matrix A [ 12 -16  14 -16]
Es una matriz diagonal dominante


In [ ]:
A0 = np.array([[10,7,8,7],
              [7,5,6,5],
              [8,6,10,9],
              [7,5,9,10]])

y = np.array([[32],
              [23],
              [33],
              [31]])

x = np.linalg.solve(A0,y)

print(x)
print(np.linalg.cond(A0, p=1))
print(np.linalg.cond(A0, p=2))
print(np.linalg.cond(A0, p=np.inf))

[[1.]
 [1.]
 [1.]
 [1.]]
4488.000000000057
2984.0927016757555
4488.000000000056
